---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marsbewk/website-backend
    - cd $DEPLOYPATH
    - npm install --production
    - rm -rf $DEPLOYPATH/tmp
    - mkdir -p $DEPLOYPATH/tmp
    - touch $DEPLOYPATH/tmp/restart.txt