---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marsbewk/repositories/backend
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/tmp && touch $DEPLOYPATH/tmp/restart.txt